### ISSUE TITLE
Compile cl-gd-glue.c fail

### ISSUE THREAD

**Issue by peebz** [edicl/cl-gd#10]
Hi,

Following the instructions, I've installed cl-gd via Quicklisp and then attempted to compile cl-gd-glue.c using make (I'm using Ubuntu 17.04).  However I receive the error:

`gcc -I/usr/local/include -fPIC -c cl-gd-glue.c`
`cl-gd-glue.c:29:16: fatal error: gd.h: No such file or directory`
`#include "gd.h"`

`compilation terminated.`
`Makefile:4: recipe for target 'cl-gd-glue.so' failed`
`make: *** [cl-gd-glue.so] Error 1`

and the header file is missing from the directory.

David

**Comment by hanshuebner** [comment]
You will need to install the gd development package in your system first, it might be called libgd-dev or gd-devel or the like.  Use your system's package management facilities to find out.

**Comment by peebz** [comment]
Many thanks for your quick reply and apologies for the question.  I should have read the instructions more closely.

David
